import datetime
import os


def export_markdown_file(
    filepath: str,
    repo_name: str,
    repo_url: str,
    source_license: str,
    prompt_content: str,
) -> bool:
    """Exports session prompt as a clean Markdown file with mandatory license attribution footer."""
    try:
        date_str = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        attribution_footer = f"""

---
## Responsible Use & License Attribution Notice
- **Repository Name**: {repo_name}
- **Repository URL**: {repo_url}
- **Detected Source License**: {source_license}
- **Export Timestamp**: {date_str}
- **Notice**: Generated by Git Reverse. Recreated prompt structures preserve original repository license compliance.
"""
        full_content = prompt_content.rstrip() + attribution_footer
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(full_content)
        return True
    except Exception:
        return False


def export_pdf_file(
    filepath: str,
    repo_name: str,
    repo_url: str,
    source_license: str,
    prompt_content: str,
) -> bool:
    """Exports session prompt as a Vercel Geist-styled PDF file.

    Uses WeasyPrint if available, or produces a standalone print-optimized HTML document.
    """
    try:
        date_str = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        html_content = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Git Reverse — {repo_name}</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Geist:wght@400;600&family=Geist+Mono&display=swap');
        
        body {{
            font-family: 'Geist', 'Helvetica Neue', Arial, sans-serif;
            background-color: #ffffff;
            color: #171717;
            padding: 40px;
            font-size: 13px;
            line-height: 1.6;
        }}
        .header {{
            border-bottom: 2px solid #171717;
            padding-bottom: 15px;
            margin-bottom: 25px;
        }}
        .title {{
            font-size: 24px;
            font-weight: 600;
            letter-spacing: -0.8px;
            margin: 0;
            color: #171717;
        }}
        .meta {{
            font-size: 11px;
            font-family: 'Geist Mono', monospace;
            color: #71717a;
            margin-top: 6px;
        }}
        .badge {{
            display: inline-block;
            background-color: #f4f4f5;
            border: 1px solid #e4e4e7;
            border-radius: 4px;
            padding: 2px 6px;
            font-size: 10px;
            font-weight: 600;
            color: #171717;
        }}
        .content {{
            background-color: #fafafa;
            border: 1px solid #e4e4e7;
            border-radius: 8px;
            padding: 20px;
            white-space: pre-wrap;
            font-family: 'Geist Mono', monospace;
            font-size: 11px;
            line-height: 1.6;
        }}
        .footer {{
            margin-top: 40px;
            padding-top: 15px;
            border-top: 1px solid #e4e4e7;
            font-size: 10px;
            color: #71717a;
            font-family: 'Geist Mono', monospace;
        }}
    </style>
</head>
<body>
    <div class="header">
        <h1 class="title">Git Reverse — System Recreation Prompt</h1>
        <div class="meta">
            Repository: <strong>{repo_name}</strong> | URL: {repo_url} | License: <span class="badge">{source_license}</span>
        </div>
    </div>
    <div class="content">{prompt_content}</div>
    <div class="footer">
        Exported on {date_str} via Git Reverse Desktop. Source License: {source_license}. All rights reserved.
    </div>
</body>
</html>
"""
        # Attempt WeasyPrint conversion if installed
        try:
            from weasyprint import HTML
            HTML(string=html_content).write_pdf(filepath)
            return True
        except Exception:
            # Fallback to HTML print document if WeasyPrint system DLLs are missing
            out_file = filepath if filepath.endswith(".html") else filepath + ".html"
            with open(out_file, "w", encoding="utf-8") as f:
                f.write(html_content)
            return True

    except Exception:
        return False
