import datetime
import os


def export_markdown_file(
    filepath: str,
    repo_name: str,
    repo_url: str,
    source_license: str,
    prompt_content: str,
) -> bool:
    """Exports session prompt as a clean Markdown file with official brand watermark and license attribution footer."""
    try:
        date_str = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        brand_header = f"""<!-- 
  GIT REVERSE INTELLIGENCE SYSTEM — OFFICIAL BRAND ARTIFACT
  Brand Palette: Dark #141413 | Light #FAF9F5 | Accent #D97757
-->
> **GIT REVERSE INTELLIGENCE SYSTEM — OFFICIAL BRAND RECREATION PROMPT**  
> *Repository: `{repo_name}` | Exported: {date_str}*

"""
        attribution_footer = f"""

---
## Responsible Use & License Attribution Notice
- **Repository Name**: {repo_name}
- **Repository URL**: {repo_url}
- **Detected Source License**: {source_license}
- **Export Timestamp**: {date_str}
- **Brand System**: Git Reverse Intelligence System (Official Brand Release)
- **Notice**: Generated by Git Reverse. Recreated prompt structures preserve original repository license compliance.
"""
        full_content = brand_header + prompt_content.rstrip() + attribution_footer
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(full_content)
        return True
    except Exception:
        return False


def export_pdf_file(
    filepath: str,
    repo_name: str,
    repo_url: str,
    source_license: str,
    prompt_content: str,
) -> bool:
    """Exports session prompt as an officially branded PDF/HTML document.

    Applies official brand guidelines:
    - Primary Dark: #141413, Light Background: #faf9f5, Primary Accent: #d97757, Secondary: #6a9bcc
    - Typography: Poppins for headings, Lora for body text, Geist Mono for code.
    - Watermark: Diagonal semi-transparent brand watermark stamp across pages.
    """
    try:
        date_str = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        html_content = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Git Reverse — {repo_name}</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@600;700&family=Lora:ital,wght@0,400;0,600;1,400&family=Geist+Mono&display=swap');

        @page {{
            size: A4;
            margin: 20mm;
            @bottom-right {{
                content: "OFFICIAL BRAND ARTIFACT • GIT REVERSE";
                font-family: 'Poppins', sans-serif;
                font-size: 8pt;
                color: #b0aea5;
            }}
        }}

        body {{
            font-family: 'Lora', Georgia, serif;
            background-color: #faf9f5;
            color: #141413;
            padding: 30px;
            font-size: 13px;
            line-height: 1.6;
            position: relative;
        }}

        /* Official Diagonal Brand Watermark */
        .watermark {{
            position: fixed;
            top: 40%;
            left: 10%;
            width: 80%;
            text-align: center;
            font-family: 'Poppins', Arial, sans-serif;
            font-size: 44px;
            font-weight: 700;
            color: rgba(217, 119, 87, 0.07);
            letter-spacing: 4px;
            transform: rotate(-30deg);
            pointer-events: none;
            z-index: 9999;
            text-transform: uppercase;
        }}

        .brand-header {{
            border-bottom: 3px solid #d97757;
            padding-bottom: 16px;
            margin-bottom: 24px;
        }}

        .brand-badge {{
            display: inline-block;
            background-color: #d97757;
            color: #faf9f5;
            font-family: 'Poppins', sans-serif;
            font-size: 9px;
            font-weight: 600;
            text-transform: uppercase;
            letter-spacing: 1px;
            padding: 3px 8px;
            border-radius: 4px;
            margin-bottom: 8px;
        }}

        .title {{
            font-family: 'Poppins', Arial, sans-serif;
            font-size: 26px;
            font-weight: 700;
            letter-spacing: -0.5px;
            margin: 4px 0 0 0;
            color: #141413;
        }}

        .meta {{
            font-size: 11px;
            font-family: 'Poppins', sans-serif;
            color: #788c5d;
            margin-top: 8px;
        }}

        .license-badge {{
            display: inline-block;
            background-color: #e8e6dc;
            border: 1px solid #b0aea5;
            border-radius: 4px;
            padding: 2px 8px;
            font-size: 10px;
            font-weight: 600;
            color: #141413;
        }}

        .content-box {{
            background-color: #ffffff;
            border: 1px solid #e8e6dc;
            border-left: 4px solid #6a9bcc;
            border-radius: 8px;
            padding: 22px;
            white-space: pre-wrap;
            font-family: 'Geist Mono', 'Consolas', monospace;
            font-size: 11px;
            line-height: 1.5;
            box-shadow: 0 1px 3px rgba(20, 20, 19, 0.05);
        }}

        .footer {{
            margin-top: 40px;
            padding-top: 15px;
            border-top: 1px solid #e8e6dc;
            font-size: 10px;
            color: #b0aea5;
            font-family: 'Poppins', sans-serif;
            display: flex;
            justify-content: space-between;
        }}
    </style>
</head>
<body>
    <div class="watermark">GIT REVERSE • OFFICIAL BRAND ARTIFACT</div>
    
    <div class="brand-header">
        <div class="brand-badge">Official Brand Release</div>
        <h1 class="title">Git Reverse — System Recreation Prompt</h1>
        <div class="meta">
            Repository: <strong>{repo_name}</strong> | URL: {repo_url} | License: <span class="license-badge">{source_license}</span>
        </div>
    </div>
    
    <div class="content-box">{prompt_content}</div>
    
    <div class="footer">
        <span>Exported on {date_str} via Git Reverse Intelligence System.</span>
        <span>Source License: {source_license}</span>
    </div>
</body>
</html>
"""
        # Attempt WeasyPrint conversion if installed
        try:
            from weasyprint import HTML
            HTML(string=html_content).write_pdf(filepath)
            return True
        except Exception:
            # Fallback to HTML print document if WeasyPrint system DLLs are missing
            out_file = filepath if filepath.endswith(".html") else filepath + ".html"
            with open(out_file, "w", encoding="utf-8") as f:
                f.write(html_content)
            return True

    except Exception:
        return False
